### ISSUE TITLE
Log in with Google button error

### ISSUE THREAD

**Issue by kbuffardi** [codewit-us/codewit.us#31]
After launching (via docker compose) I can load localhost, but when I click on the "Log in with  Google" button, the browser reports the error (default white screen, not within our UI):

```
This page isn’t working
localhost is currently unable to handle this request.
HTTP ERROR 500
```

Vite is reporting to the console:
```
[vite] http proxy error: /oauth2/google
Error: getaddrinfo ENOTFOUND app
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
```

**Comment by numan-7** [comment]
I have not been able to replicate this issue. When I press login with google it works perfectly for me.

**Comment by kbuffardi** [comment]
I got it working on my machine this time after troubleshooting some other network problems on it. Closing this with the assumption that it was the computer's networking that was causing the error.
