### ISSUE TITLE
Update Exercise creation and view pages

### ISSUE THREAD

**Issue by kbuffardi** [codewit-us/codewit.us#33]
This issue corresponds to the backend changes specified in #32 

1. Update the Exercise creation page so it includes extra fields:
    - A dropdown of which language it uses (corresponding with the existing Language library)
    - A code editing text field, so the author can specify the testing script

2. Update the Exercise view page so that if a user is logged in, there is a **Submit** button that will submit the information to the backend to process as an Attempt (see #32)

*Note: we are not yet running the tests on the submitted attempts yet. The experimental containerized code evaluation still needs to be finalized before we add that functionality**

**Comment by numan-7** [comment]
_A dropdown of which language it uses (corresponding with the existing Language library)_

We already have this if I'm not mistaken.

**Comment by kbuffardi** [comment]
> _A dropdown of which language it uses (corresponding with the existing Language library)_
> 
> We already have this if I'm not mistaken.

You're right.
